services:
    _defaults:
        autowire: true
        autoconfigure: true

    DevTools\Repository\Paginator:
        arguments: ['@knp_paginator']

    DevTools\Validator\SortFieldsValidator: ~

    DevTools\Doctrine\MySql\Event\DBALSchemaEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    DevTools\Utils\TokenGeneratorInterface:
        class: DevTools\Utils\TokenGenerator

    DevTools\FosRest\Serializer\SymfonySerializerAdapter:
        arguments: ['@serializer']

    DevTools\FosRest\ParamConverter\CommandQueryParamConverter:
        tags:
            - { name: 'request.param_converter', converter: 'command_query', priority: 102 }

    DevTools\FosRest\Serializer\FlattenExceptionNormalizer:
        decorates: 'fos_rest.serializer.flatten_exception_handler'
        arguments: [ '@DevTools\FosRest\Serializer\FlattenExceptionNormalizer.inner' ]

    DevTools\FosRest\ErrorHandler\ErrorRenderer:
        decorates: 'error_renderer'
        arguments: [ '@DevTools\FosRest\ErrorHandler\ErrorRenderer.inner' ]
