services:
    _defaults:
        autowire: true
        autoconfigure: true

    DevTools\Repository\Paginator: ~

    DevTools\Validator\SortFieldsValidator: ~
    DevTools\Validator\UniqueEntityValidator: ~
    DevTools\Validator\EntityExistValidator: ~

    DevTools\Doctrine\MySql\Event\DBALSchemaEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    DevTools\Utils\TokenGeneratorInterface:
        class: DevTools\Utils\TokenGenerator

    DevTools\FosRest\Serializer\SymfonySerializerAdapter:
        arguments: ['@serializer']

    DevTools\FosRest\ParamConverter\DataNormalizer:
        arguments: ['@serializer.name_converter.metadata_aware']

    DevTools\FosRest\ParamConverter\DataExtractor:
        arguments: ['@serializer.name_converter.metadata_aware']

    DevTools\FosRest\ParamConverter\CommandQueryParamConverter:
        tags:
            - { name: 'request.param_converter', converter: 'command_query', priority: 102 }

    DevTools\FosRest\Serializer\FlattenExceptionNormalizer:
        decorates: 'fos_rest.serializer.flatten_exception_normalizer'
        arguments:
            - '@DevTools\FosRest\Serializer\FlattenExceptionNormalizer.inner'
            - '@serializer.name_converter.metadata_aware'

    DevTools\FosRest\EventListener\ResponseStatusCodeListener:
        decorates: 'fos_rest.exception.response_status_code_listener'
        arguments:
            - '@DevTools\FosRest\EventListener\ResponseStatusCodeListener.inner'

    DevTools\FosRest\ErrorHandler\ErrorRenderer:
        decorates: 'error_renderer'
        arguments: [ '@DevTools\FosRest\ErrorHandler\ErrorRenderer.inner' ]

    DevTools\Response\Includes\RetrieverLocator: ~
    DevTools\Response\Includes\Parser: ~
    DevTools\Response\Includes\Resolver:
        arguments: ['@serializer.name_converter.metadata_aware']

    DevTools\Serializer\EnumNormalizer:
        tags: [ 'serializer.normalizer' ]

    DevTools\UnitTest\Fixtures\AggregateRootProcessor:
        tags: [ 'fidry_alice_data_fixtures.processor' ]

    DevTools\Messenger\ObjectMapper: ~